### ISSUE TITLE
[Arcs] Guild Investigators Infinite Loops

### ISSUE THREAD

**Issue by ledergamesmatt** [LederCards/cards#32]
We identified a few scenarios where the Guild Investigator can be used to generate infinite loop with payoff that outright wins the game. Not sure how serious they are given they do require some set up. But perhaps worth looking at

[https://discord.com/channels/476234833572397056/1263203780070084712](https://discord.com/channels/476234833572397056/1263203780070084712)

**Comment by jdyearsley** [comment]
I'm going to let these lie. It is an incredibly rare situation, it's only in campaign play (so not a risk for trad competitive play), and it only really makes you go infinite if you do this after everyone else has run out of cards and thus cannot block you in the Court, and there's at least 1 card in the Court with no Rival agents. 

I also don't see how this actually makes you win the game. You basically just get to build a lot of stuff in places you already are, so you're limited by planet slots and by your ship supply.
