### ISSUE TITLE
[Arcs] Arsenal Keepers + Monopoly interaction

### ISSUE THREAD

**Issue by jdyearsley** [LederCards/cards#35]
Arsenal Keepers should let you take Weapons off a Monopoly you get. However, this wreaks havoc with the "take" definition as originally laid out in the base rulebook.

**Comment by turmoilbyrd** [comment]
My thought is, if the Peace Keeper is winning the Weapon monopoly, they very likely already have 3+ weapons on the Arsenal. So whether the other 1-2 weapons are transferred onto the Arsenal automatically is a really minor difference and probably not worth the trouble.

**Comment by jdyearsley** [comment]
That's more than fair. I'll stick to the intuitive take here and leave it be.

**Comment by yggdrasilsYeoman** [comment]
This question still arose recently [in the Discord](https://discord.com/channels/476234833572397056/963112189802201108/1332168761926488178); it does seem an FAQ saying the Monopoly resources _don't_ transfer is warranted.
