### ISSUE TITLE
[Arcs] Held resources being Stolen

### ISSUE THREAD

**Issue by ledergamesmatt** [LederCards/cards#39]
We added this text:
> Some cards say they hold resources. These resources can be spent and add to ambitions, but **they can be stolen only as the card describes**..

The clause in bold is making some people think that if a card doesn't explicitly say the resource on it can be stolen, then they can't be stolen. Perhaps this can be rephrased.

**Comment by turmoilbyrd** [comment]
I see it is now changed to

> They cannot be stolen unless explicitly allowed

Is this the new and final phrasing? This means resources cannot be stolen off [Merchant League.](https://cards.ledergames.com/card/ARCS-F302)

**Comment by jdyearsley** [comment]
The final wording should be:
> They cannot be stolen **in battle** unless explicitly allowed

This is meant to clarify that resources don't gain their holding card's key value for the purpose of raiding. I've edited the errata and clarifications doc to reflect this.
