### ISSUE TITLE
[Arcs] Golem limbo state?

### ISSUE THREAD

**Issue by turmoilbyrd** [LederCards/cards#54]
https://discord.com/channels/476234833572397056/963112189802201108/1294731916213354588

Do Golems spent in prelude stay in "the limbo state" until end of prelude, like resources? Or are they immediately flipped and put into somebody's resource slot. This could matter if someone wants to raid a golem after spending it.

**Comment by jdyearsley** [comment]
No, they aren't resources so they don't enter limbo RAW. Certainly if somebody finds an infinite combo I may introduce it.
