### ISSUE TITLE
[Arcs] Clarify cartel guild card discard prelude ability 

### ISSUE THREAD

**Issue by fallspectrum** [LederCards/cards#67]
Can you discard cartel cards during prelude even if there are no associated resources to steal from other players?  Would be helpful to clarify this for both cartel cards.

**Comment by turmoilbyrd** [comment]
Duplicate of https://github.com/LederCards/cards/issues/31

**Comment by fallspectrum** [comment]
Will leave this open as an indirect means of bumping the relevance of #31 until someone else closes it.

**Comment by jdyearsley** [comment]
Will answer #31
