### ISSUE TITLE
How long does a Monopoly holder’s forced consent last for?

### ISSUE THREAD

**Issue by isaac-lf** [LederCards/cards#73]
We know that a Monopoly holder’s consent can only be forced in the Call to Order by the Summit caller, but how long does a Monopoly holder’s forced consent last for exactly?

A single Transfer Asset action? i.e.
- The Summit caller (Player A) must return two favors to the Material Monopoly holder (Player B) if they want to force Player C to give them two Material resources - or if they want to force Player C and Player D to give them one Material resource each

The duration of the Call to Order? i.e.
- The Summit caller (Player A) must return just one favor to the Material Monopoly holder (Player B) in either of the above situations

The entirety of the Summit (Call to Order + Negotiations)? i.e.
- After the Summit caller (Player A) returns a favor to the Material Monopoly holder (Player B) to force their consent in the Call to Order, Player C can give Player D a Material resource during Negotiations without needing Player B’s express consent, which otherwise must be given freely

I think most people would assume it is only for a single Transfer Asset action but the existence of Summit cards like Peace Accords and Guild Negotiations - which allow players to force consent even if they didn’t call the Summit - causes some confusion because Monopoly Consent is much more restrictive by comparison.

**Comment by turmoilbyrd** [comment]
> which allow players to force consent even if they didn’t call the Summit
I don't think that's how those cards work that way.

In short the Monopoly consent is on a per-action basis.

**Comment by turmoilbyrd** [comment]
I think all consent are on a per-action basis and there is no reason to believe otherwise.
