### ISSUE TITLE
[Arcs] Breaking World should not destroy the Flagship buildings

### ISSUE THREAD

**Issue by turmoilbyrd** [LederCards/cards#80]
The [Breaking World](https://cards.ledergames.com/card/ARCS-F1103B) card (post errata) says 

> Destroy all buildings on the planet, placing them here, not in Trophies. Nobody Ransacks the Court

It technically doesn't say "on the map" for the [building check](https://arcs.seiyria.com/#20.6.1-building-checks) rule, but I understand that "on the planet" is just a special case as "on the map"?

**Comment by jdyearsley** [comment]
Correct. "On the planet" should be understood as a subset of "on the map."

Is this a widespread confusion, or just a question you have?

**Comment by turmoilbyrd** [comment]
> Correct. "On the planet" should be understood as a subset of "on the map."
> 
> Is this a widespread confusion, or just a question you have?

I think this was just me trying to more literal. I think the assumption is reasonable
